<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login | DSI-ISET-BIzerte</title>
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="css/bootstrap.min.css">
</head>
<body>
<section id="nav-bar">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="index.html"><img src="logo.svg"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                      <a class="nav-link" href="login.php">Login</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="index.html#contactus">Contact-Us </a>
                    </li>
                  </ul>
                </div>
         </nav>
</section>
<section class="container">
    <div class="container">
        <div class="row">
            <div class="col-lg-10">
                <?php if (isset($auth_error)): ?>
                    <div class="alert alert-danger alert-dismissible fade show">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <?= $auth_error ?>
                    </div>
                <?php endif ?>
                <br>
                <fieldset>
                    <legend>Log in</legend>
                    <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">
                        <div class="form-group ">
                            <label>E-mail</label>
                            <input type="email" name="email" class="form-control" value="<?= $_POST['email'] ?? '' ?>" maxlength="50" required="">
                            <span class="text-danger"><?php if (isset($email_error)) echo $email_error; ?></span>
                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            <input type="password" name="pwd" class="form-control" value="" required="">
                            <span class="text-danger"><?php if (isset($pwd_error)) echo $pwd_error; ?></span>
                        </div>  
                        <input type="submit" id="mybtn" class="btn btn-lg btn-block" name="login" value="Submit">
                        <br>
                        <span>You don't have account?<a href="register.php" class="mt-3"> Click Here</a></span>
                    </form>
                </fieldset>
            </div>
        </div>     
    </div>
                </section>
                <section id="footer">
    <div class="container text-center">
        <p>ISET Bizerte</p>
    </div>
</section>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="js/bootstrap.min.js" ></script>
        <script src="js/smooth-scroll.js"></script>
        <script src="https://kit.fontawesome.com/0d23adf6ea.js" crossorigin="anonymous"></script>
</body>
</html>