<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login | DSI-ISET-BIzerte</title>
    <link rel="stylesheet" href=".\css\bootstrap.css">
    <script src="https://kit.fontawesome.com/7f1324c4ec.js" crossorigin="anonymous"></script>
    <script src=".\js\bootstrap.js"></script>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-lg-10">
                <?php if (isset($auth_error)): ?>
                    <div class="alert alert-danger alert-dismissible fade show">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <?= $auth_error ?>
                    </div>
                <?php endif ?>
                <fieldset>
                    <legend>Log in</legend>
                    <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">
                        <div class="form-group ">
                            <label>E-mail</label>
                            <input type="email" name="email" class="form-control" value="<?= $_POST['email'] ?? '' ?>" maxlength="50" required="">
                            <span class="text-danger"><?php if (isset($email_error)) echo $email_error; ?></span>
                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            <input type="password" name="pwd" class="form-control" value="" required="">
                            <span class="text-danger"><?php if (isset($pwd_error)) echo $pwd_error; ?></span>
                        </div>  
                        <input type="submit" class="btn btn-primary" name="login" value="Submit">
                        <br>
                        <span>You don't have account?<a href="register.php" class="mt-3">Click Here</a></span>
                    </form>
                </fieldset>
            </div>
        </div>     
    </div>
</body>
</html>