
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <title>Document</title>
</head>
<body>
  <?php include 'classes/product.class.php';  ?>
<section id="nav-bar">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="customdashboard.php"><img src="logo.svg"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                      <a class="nav-link" href="acccustom.php">ACCOUNT</a>
                    </li>
                  <li class="nav-item active">
                      <a class="nav-link" href="product.phtml">Menu <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="customdashboard.php#contactus">Contact-Us </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="logout.php">Logout</a>
                    </li>
                  </ul>
                </div>
          </nav>
</section>
<?php
$cart = new product;
$products=$cart->getdata();
?>
   <div class="container">
  <?php
  foreach ($products as $product):
    
  ?>
  <form method="post" action="product.php?id=<?php echo $product->pid; ?>">
  <div class="row">
    <div class="col-md">
    <img  class="prod-img"   src="<?php echo $product->file; ?>" alt="error" >
    <h4><?php echo $product->name; ?></h4>
    <span class="text-info"><?php echo $product->description; ?></span>
    <h4 class="form-control"><?php echo number_format($product->price,2); ?> TND</h4>
    <input type="hidden" name="name" value="<?php echo $product->name; ?>">
    <input type="hidden" name="price" value="<?php echo $product->price; ?>">
    <input type="number" class="form-control" name="quantity" value="1">
    <input type="submit" name="add_cart" value="add to cart" class="btn btn-info">
  </div>
  </div>
  </form>
  <?php 

endforeach; ?>
 
   <div class="table-responsive">
   <table class="table">
   <tr><th><h1> order details</h1></th></tr>
   <th>product name</th>
   <th>quantity</th>
   <th>price</th>
   <th>total</th>
   <?php
    
   if (!empty ($_SESSION['shopping_cart'])):
    $total=0;
    foreach($_SESSION['shopping_cart'] as $key=>$produit):
   ?>
  <tr>
  <td><?php echo $produit['name']; ?></td>
  <td><?php echo $produit['quantity']; ?></td>
  <td><?php echo $produit['price']; ?></td>
  <td><?php echo $produit['quantity']* $produit['price']." TND"; ?></td>
  </tr>
  <?php 
    
    $total += $produit['quantity']* $produit['price'];
  endforeach; ?>
  <tr>
<td colspan="5" >
<strong>TOTAL: <?php echo $total." TND"; ?></strong>
</td>
</tr>
<?php 
endif;

   ?>

   </table>
   </div>
   </div>
   <section id="footer">
    <div class="container text-center">
        <p>ISET Bizerte</p>
    </div>
</section>
</body>
</html>