<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href=".\css\bootstrap.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/7f1324c4ec.js" crossorigin="anonymous"></script>
    <script src=".\js\bootstrap.js"></script>
    <title>Document</title>
</head>
<body>
    <div class="container">
        <fieldset>
            <legend>REGISTERATION EMPLOYEE</legend>
            <form action="" method="post">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" name="name" class="form-control" value="<?= $_POST['name'] ?? '' ?>" maxlength="50" required="required">
                            <span class="text-danger"><?php if (isset($name_error)) echo $name_error; ?></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="phone">Phone</label>
                            <input type="tel" name="phone" class="form-control" value="<?= $_POST['phone'] ?? '' ?>" maxlength="50" required="required">
                            <span class="text-danger"><?php if (isset($phone_error)) echo $phone_error; ?></span>
                        </div>
                    </div>
                </div>  
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="email">E-mail</label>
                            <input type="email" name="email" class="form-control" value="<?= $_POST['email'] ?? '' ?>" maxlength="50" required="required">
                            <span class="text-danger"><?php if (isset($email_error)) echo $email_error; ?></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="pwd">Password</label>
                            <input type="password" name="pwd" class="form-control" required="required">
                            <span class="text-danger"><?php if (isset($pwd_error)) echo $pwd_error; ?></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="conpwd">Confirme password</label>
                            <input type="password" name="conpwd" class="form-control" required="required">
                            <span class="text-danger"><?php if (isset($conpwd_error)) echo $conpwd_error; ?></span>
                        </div>
                    </div>
                </div>
                <input type="submit" class="btn btn-block btn-primary" name="signup" value="submit">
                <button type="reset" class="btn btn-outline-danger"><i class="fas fa-redo-alt"></i> Reset</button>
            </form>
        </fieldset>
    </div>
</body>
</html>